version: '3.8'

services:
  wordpress:
    build: ./wordpress # Esta línea apunta al directorio donde está el Dockerfile
    container_name: wordpress
    ports:
      - "8080:80"  # Accede a WordPress a través de http://localhost:8080
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html  # Volumen para persistir los datos de WordPress
    networks:
      - wordpress_network

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql  # Volumen para persistir los datos de la base de datos
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_network:

